import java.io.File;
import java.util.ArrayList;


public class QuizMachine extends javax.swing.JFrame {

    ArrayList<String> questionList = new ArrayList();
    ArrayList<String> answerList = new ArrayList();
    ArrayList<Boolean> correctAnswers = new ArrayList();
    
    int numberOfQuestion = 1;
    String filePath = "";
    
    public QuizMachine() {
        initComponents();
        PlayQuiz.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PlayQuiz = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        answer2 = new javax.swing.JTextField();
        answer4 = new javax.swing.JTextField();
        answer3 = new javax.swing.JTextField();
        answer1 = new javax.swing.JTextField();
        CheckBox1 = new javax.swing.JCheckBox();
        CheckBox2 = new javax.swing.JCheckBox();
        CheckBox3 = new javax.swing.JCheckBox();
        CheckBox4 = new javax.swing.JCheckBox();
        counterLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pickCountLbl = new javax.swing.JLabel();
        nxtQuestionBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        playQuizbtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        QuitBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Machine");

        jLabel1.setText("Quiz Title:");

        jLabel2.setText("Question no:");

        jLabel3.setText("Question:");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jLabel4.setText("Answers:");

        CheckBox1.setText("Correct");

        CheckBox2.setText("Correct");

        CheckBox3.setText("Correct");

        CheckBox4.setText("Correct");

        jLabel5.setText("Please tick:");

        nxtQuestionBtn.setText("Next Question");
        nxtQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtQuestionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlayQuizLayout = new javax.swing.GroupLayout(PlayQuiz);
        PlayQuiz.setLayout(PlayQuizLayout);
        PlayQuizLayout.setHorizontalGroup(
            PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayQuizLayout.createSequentialGroup()
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayQuizLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlayQuizLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PlayQuizLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PlayQuizLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(counterLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PlayQuizLayout.createSequentialGroup()
                                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PlayQuizLayout.createSequentialGroup()
                                        .addComponent(answer4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBox4))
                                    .addGroup(PlayQuizLayout.createSequentialGroup()
                                        .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBox3))
                                    .addGroup(PlayQuizLayout.createSequentialGroup()
                                        .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBox2))
                                    .addGroup(PlayQuizLayout.createSequentialGroup()
                                        .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(CheckBox1))
                                    .addComponent(pickCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nxtQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PlayQuizLayout.setVerticalGroup(
            PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(counterLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(answer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox2))
                .addGap(10, 10, 10)
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBox4))
                .addGroup(PlayQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayQuizLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayQuizLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(pickCountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nxtQuestionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PlayQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setToolTipText("");
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("File");

        playQuizbtn.setText("Play Quiz");
        playQuizbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playQuizbtnActionPerformed(evt);
            }
        });
        jMenu1.add(playQuizbtn);
        jMenu1.add(jSeparator1);

        QuitBtn.setText("Quit");
        QuitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitBtnActionPerformed(evt);
            }
        });
        jMenu1.add(QuitBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("about");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playQuizbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playQuizbtnActionPerformed
        PlayQuiz.setVisible(true);
        
        numberOfQuestion = 1;
        counterLbl.setText(numberOfQuestion + "");
        
        filePath = FileIO.showOpenDialog();
        
        String readfile = FileIO.readTextFile(filePath);
        String pathName = getQuizNameFromPath(filePath);
        
        titleLbl.setText(pathName);
        
        fillUpArrays(readfile);
        showQuestion(numberOfQuestion);
    }//GEN-LAST:event_playQuizbtnActionPerformed

    private void QuitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitBtnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AboutFrame s = new AboutFrame();
        s.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void nxtQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtQuestionBtnActionPerformed
        
        numberOfQuestion += 1;
        counterLbl.setText(numberOfQuestion + "");
        
        if(numberOfQuestion == 1)
        {
            showQuestion(numberOfQuestion);
        }   
        else
        {
            /*
            for(int i = numberOfQuestion -1; i < questionList.size(); i++)
            {
                txtArea.setText(questionList.get(i));

                answer1.setText(answerList.get(i*4));
                answer2.setText((answerList.get(i*4)+1));
                answer3.setText((answerList.get(i*4)+2));
                answer4.setText((answerList.get(i*4)+3));
            }
            */
        }
        
    }//GEN-LAST:event_nxtQuestionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizMachine().setVisible(true);
            }
        });
    }

     public static String getQuizNameFromPath(String Path)
    {
        File newFile = new File(Path);
        
        String fileName = newFile.getName();
        String name = fileName.substring(0,fileName.length()-4);
        return name;
    }
    
      public void clearAll() 
    {
            txtArea.setText("");
            answer1.setText("");
            answer2.setText("");
            answer3.setText("");
            answer4.setText("");

            CheckBox1.setSelected(false);
            CheckBox2.setSelected(false);
            CheckBox3.setSelected(false);
            CheckBox4.setSelected(false);
    }
    
    public void fillUpArrays(String readline)
    {
        String[] files = readline.split("\\$|\\;");
        String[] files2 = readline.split("\\?|\\;");
        
        for(int j = 1; j < files.length; j++)
        {
            if(files[j].endsWith("?"))
            {
                questionList.add(files[j]);
            }
        }
        
        for(int a = 1; a < files2.length; a++)
        {
           if(files2[a].endsWith("."))
           {
              answerList.add(files2[a].substring(files2[a].indexOf(",")+1,files2[a].indexOf(".")));
           }
        }
        
        for(int b = 1; b < files.length; b++)
        {   
            if(files[b].contains("true") || files[b].contains("false"))
            {
                boolean trueOrFalse  = Boolean.parseBoolean(files[b].substring(0,files[b].indexOf(",")));
                correctAnswers.add(trueOrFalse);
            }
        }
        
        System.out.println(questionList);
        System.out.println(answerList);
        System.out.println(correctAnswers);
        
//        for(int i = 1; i < files.length; i++)
//        {
//            System.out.println(files[i]);
//        }
    }  
      
    public void showQuestion(int numberOfQuestion)
    {    
           txtArea.setText(questionList.get(0));

           answer1.setText(answerList.get(0));
           answer2.setText(answerList.get((1))); 
           answer3.setText(answerList.get((2)));
           answer4.setText(answerList.get((3)));
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox1;
    private javax.swing.JCheckBox CheckBox2;
    private javax.swing.JCheckBox CheckBox3;
    private javax.swing.JCheckBox CheckBox4;
    private javax.swing.JPanel PlayQuiz;
    private javax.swing.JMenuItem QuitBtn;
    private javax.swing.JTextField answer1;
    private javax.swing.JTextField answer2;
    private javax.swing.JTextField answer3;
    private javax.swing.JTextField answer4;
    private javax.swing.JLabel counterLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton nxtQuestionBtn;
    private javax.swing.JLabel pickCountLbl;
    private javax.swing.JMenuItem playQuizbtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
